import type { Metadata } from 'next';
import './globals.css';
import { Sidebar } from '@/components/sidebar/sidebar';
import { inter } from '@/components/ui/fonts';

//import { Suspense } from 'react';


export const metadata: Metadata = {
  title: 'Sam on Programming',
  description: 'Generated by create next app and then modified to be a neat site you like hopefully. ',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body className={`${inter.className} antialiased`}>
          <Sidebar />
        <main className='mx-5 mt-16 sm:ml-[300px] sm:mt-3'>{children}</main>
      </body>
    </html>
  );
}